-- 코드를 입력하세요
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
FROM BOOK B, AUTHOR A, BOOK_SALES BS
WHERE B.AUTHOR_ID = A.AUTHOR_ID
AND B.BOOK_ID = BS.BOOK_ID
AND TO_CHAR(BS.SALES_DATE, 'YYYYMM') = '202201'
GROUP BY B.AUTHOR_ID, B.CATEGORY, A.AUTHOR_NAME
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC
;