-- 코드를 입력하세요
SELECT TO_NUMBER(TO_CHAR(A.START_DATE, 'MM')) AS MONTH, B.CAR_ID, COUNT(A.CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
, (SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE TO_CHAR(START_DATE, 'YYYYMM') >= '202208' 
AND TO_CHAR(START_DATE, 'YYYYMM')<='202210'
GROUP BY CAR_ID
HAVING COUNT(CAR_ID)>=5) B
WHERE A.CAR_ID = B.CAR_ID
AND TO_CHAR(A.START_DATE, 'YYYYMM') >= '202208' 
AND TO_CHAR(A.START_DATE, 'YYYYMM')<='202210'
GROUP BY B.CAR_ID, TO_NUMBER(TO_CHAR(A.START_DATE, 'MM'))
ORDER BY MONTH ASC, CAR_ID DESC
;